#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

// Map Group 0
#define MAP_LOBBY_LEVEL_SELECT (0 | (0 << 8))

// Map Group 1
#define MAP_DUNGEON_TUTORIAL_ENTRANCE             (0 | (1 << 8))
#define MAP_DUNGEON_TUTORIAL_ACT1_GIFT1           (1 | (1 << 8))
#define MAP_DUNGEON_TUTORIAL_ACT1_ENCOUNTER1      (2 | (1 << 8))
#define MAP_DUNGEON_TUTORIAL_ACT1_BATTLE1         (3 | (1 << 8))
#define MAP_DUNGEON_TUTORIAL_ACT1_SHOP1           (4 | (1 << 8))
#define MAP_DUNGEON_TUTORIAL_ACT1_SHOP1_FORK      (5 | (1 << 8))
#define MAP_DUNGEON_TUTORIAL_ACT1_BATTLE1_FORK    (6 | (1 << 8))
#define MAP_DUNGEON_TUTORIAL_ACT1_ENCOUNTER1_FORK (7 | (1 << 8))
#define MAP_DUNGEON_TUTORIAL_ACT1_ELITE_BATTLE1   (8 | (1 << 8))
#define MAP_DUNGEON_TUTORIAL_ACT1_BOSS            (9 | (1 << 8))

// Map Group 2
#define MAP_DUNGEON_EDEN_ACT1_ENTRANCE   (0 | (2 << 8))
#define MAP_DUNGEON_EDEN_ACT1_GIFT1      (1 | (2 << 8))
#define MAP_DUNGEON_EDEN_ACT1_ENCOUNTER1 (2 | (2 << 8))

#define MAP_GROUPS_COUNT 3

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
